name: build-and-push-container-image
on:
    workflow_dispatch:
        inputs:
            environment:
                description: specify the image repository environment.
                required: true
                default: dev
            service_name:
                description: specify the service name.
                required: true
                default: terraform-tutorial
            ecr_role_name:
                description: specify the ecr role name.
                required: true
                default: app
            build_target:
                description: specify the build target branch.
                required: true
                default: master
permissions:
    id-token: write
    contents: read
jobs:
    build-and-push-container-image:
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                ref: ${{ github.event.inputs.build_target }}
            - name: Get image tag
              id: get-image-tag
              run: |
                    SHORT_COMMIT_ID=`git rev-parse --short HEAD`
                    REF=`echo ${{ github.event.inputs.build_target }} | sed -e 's/\//-/g'`
                    echo "image-tag=${REF}-${SHORT_COMMIT_ID}" >> $GITHUB_OUTPUT
            - name: Assume Role
              uses: aws-actions/configure-aws-credentials@v1
              with:
                # これGithub Ripository Secretsに設定しないとダメ(Environment Secretsじゃないよ)。iam下のterraformのapply→発行したRoleのARNを設定する
                role-to-assume: ${{ secrets.IAM_ARN_TO_PUSH_IMAGE }}
                aws-region: ap-northeast-1
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
            - name: Build and push image to Amazon ECR
              uses: docker/build-push-action@v3
              with:
                context: "image"
                push: true
                tags: ${{ steps.login-ecr.outputs.registry }}/${{ github.event.inputs.service_name }}-${{ github.event.inputs.environment }}-${{ github.event.inputs.ecr_role_name }}:${{ steps.get-image-tag.outputs.image-tag }}
